name: Publish to GCR

#
# A Workflow that will take a GitHub Packages hosted container and push it into GCR so that it can be deployed
# to a GCP environment in other workflows.
#

on:
  workflow_dispatch:
    inputs:
      container_registry:
        description: Docker Registry Container URL
        required: true
        default: docker.pkg.github.com

      container:
        decription: Container Name
        required: true
        default: octodemo/pm-demo/pm-demo

      version:
        description: Image Tag
        required: true
        default: 1.0.0-72714369

jobs:
  deploy_to_gcr:
    name: Deploy to Google Container Registry

    runs-on: ubuntu-20.04

    env:
      GCR_CONTAINER_IMAGE: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/pm-demo:${{ github.event.inputs.version }}

    steps:
      - name: Log in to GitHub Docker Package Registry
        env:
          REGISTRY_USERNAME: <token>
          REGISTRY_PASSWORD: ${{ secrets.OCTODEMO_OCTODEMOBOT_TOKEN }}
          REGISTRY_URL: ${{ github.event.inputs.container_registry }}
        run: |
          echo $REGISTRY_PASSWORD | docker login $REGISTRY_URL -u $REGISTRY_USERNAME --password-stdin                  

      - name: Pull image from GitHub Package Registry and Tag for GCR
        env:
          GITHUB_CONTAINER_IMAGE: ${{ github.event.inputs.container_registry }}/${{ github.event.inputs.container }}:${{ github.event.inputs.version }}
        run: |
          docker pull $GITHUB_CONTAINER_IMAGE
          docker tag $GITHUB_CONTAINER_IMAGE $GCR_CONTAINER_IMAGE

      # Logging in using command line utilities
      # - name: Log in to gcloud
      #   run: |
      #     echo "${{ secrets.GCP_CONTAINERS_SERVICE_ACCOUNT_KEY }}" | base64 -d > ./key.json
      #     gcloud auth activate-service-account ${{ secrets.GCP_CONTAINERS_SERVICE_ACCOUNT }} --key-file=./key.json
      #     rm ./key.json
      #
      # Logging in using an Action provided by GCP
      - name: Log in to gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          version: 303.0.0
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CONTAINERS_SERVICE_ACCOUNT_KEY }}

      - name: Upload Container to Google Container Registry
        run: |
          gcloud auth configure-docker
          docker push $GCR_CONTAINER_IMAGE
